### ISSUE TITLE
Basic Lobby

### ISSUE THREAD

**Issue by 0Bennyman** [0Bennyman/ProjectLDR#2]
So after joining or creating a game you are put into a Lobby where you wait for others to Join.

**Comment by nikolasjklein** [comment]
![sessionlobby#2](https://user-images.githubusercontent.com/39725291/62575867-f583ad80-b89b-11e9-86cf-b9bfa76d1850.png)

**Comment by 0Bennyman** [comment]
connections are maybe kind of working, now to full on test it with disconnecting and joining I guess.

**Comment by 0Bennyman** [comment]
I guess very basic functionality is done and you can now join and kick player 2, maybe need to limit it so only Host can kick him but oh well for now.
